configure: clean up tmpfile if we fail.
Reported-by: @whitslack
Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -247,7 +247,9 @@ if command -v "${PG_CONFIG}" >/dev/null; then
     POSTGRES_LDLIBS="-L$("${PG_CONFIG}" --libdir) -lpq"
 fi
 
-rm -f $CONFIG_VAR_FILE.$$
+# Clean up on exit.
+trap "rm -f $CONFIG_VAR_FILE.$$" 0
+
 $CONFIGURATOR --extra-tests --autotools-style --var-file=$CONFIG_VAR_FILE.$$ --header-file=$CONFIG_HEADER --configurator-cc="$CONFIGURATOR_CC" --wrapper="$CONFIGURATOR_WRAPPER" "$CC" ${CWARNFLAGS-$BASE_WARNFLAGS} $CDEBUGFLAGS $COPTFLAGS -I/usr/local/include -L/usr/local/lib $SQLITE3_CFLAGS $POSTGRES_INCLUDE <<EOF
 
 var=HAVE_GOOD_LIBSODIUM
